### ISSUE TITLE
how to use dragster in ES6 (or webpack)? 

### ISSUE THREAD

**Issue by xiaok** [bensmithett/dragster#12]
import Dragster from 'dragster'

console.log(Dragster)  // Object {}
new Dragster( this.el ) // Uncaught TypeError: _dragster2.default is not a function

**Comment by JamieWoodbury** [comment]
@xiaok what was the resolution to this? I'm running into the same problem, and can't seem to get it to export properly without a shim in Webpack.

``` coffeescript
Dragster = require 'exports?window.Dragster!dragster'
```

**Comment by Dinduks** [comment]
```
import 'dragster';
new Dragster($someElement);
```

**Comment by almirsarajcic** [comment]
Thanks @Dinduks. That worked!
