### ISSUE TITLE
Leave event not triggered on target drop

### ISSUE THREAD

**Issue by catmanjan** [bensmithett/dragster#4]
Drag and drop onto target, dragster enter fires the first time.

Perform same drag and drop again, dragster enter does not fire until the cursor has left and re-entered.

**Comment by catmanjan** [comment]
![dnd](https://f.cloud.github.com/assets/137350/2305923/299606e4-a273-11e3-97ca-4af94fa8ddfb.gif)

**Comment by bensmithett** [comment]
Cheers, I'll check it out. Patches welcome!

**Comment by leefernandes** [comment]
+1

**Comment by bensmithett** [comment]
This should be fixable in the latest version, #7 adds a `reset` function that you can call on `drop`.
