### ISSUE TITLE
Events are triggered many times

### ISSUE THREAD

**Issue by catmanjan** [bensmithett/dragster#5]
Should only trigger once per "action", create an interval based listener perhaps?

![image](https://f.cloud.github.com/assets/137350/2306579/0590bda8-a28b-11e3-8044-6afdc43544b9.png)

**Comment by catmanjan** [comment]
Probably linked to other listener issues, recommend moving to jquery event propagation which has workarounds for this sort of thing.

**Comment by bensmithett** [comment]
I can't reproduce this... which browser?
